export const CORPORATE_LIST = "CORPORATE_LIST";
export const CORPORATE_LIST_SUCCESSFUL = "CORPORATE_LIST_SUCCESSFUL";
export const CORPORATE_LIST_FAILED = "CORPORATE_LIST_FAILED";
export const RESET_CORPORATE_LIST_FLAG = "RESET_CORPORATE_LIST_FLAG";
export const REFRESH_CORPORATE_LIST_FLAG = "REFRESH_CORPORATE_LIST_FLAG";

export const DELETE_CORPORATE = "DELETE_CORPORATE";
export const DELETE_CORPORATE_SUCCESSFUL = "DELETE_CORPORATE_SUCCESSFUL";
export const DELETE_CORPORATE_FAILED = "DELETE_CORPORATE_FAILED";
