export const SAVE_PROJECT_CATEGORY = "SAVE_PROJECT_CATEGORY";
export const SAVE_PROJECT_CATEGORY_SUCCESSFUL = "SAVE_PROJECT_CATEGORY_SUCCESSFUL";
export const SAVE_PROJECT_CATEGORY_FAILED = "SAVE_PROJECT_CATEGORY_FAILED";

export const DELETE_PROJECT_CATEGORY = "DELETE_PROJECT_CATEGORY";
export const DELETE_PROJECT_CATEGORY_SUCCESSFUL = "DELETE_PROJECT_CATEGORY_SUCCESSFUL";
export const DELETE_PROJECT_CATEGORY_FAILED = "DELETE_PROJECT_CATEGORY_FAILED";

export const RESET_SAVE_PROJECT_CATEGORY_FLAG = "RESET_SAVE_PROJECT_CATEGORY_FLAG";
