export const TESTIMONIAL_LIST = "TESTIMONIAL_LIST";
export const TESTIMONIAL_LIST_SUCCESSFUL = "TESTIMONIAL_LIST_SUCCESSFUL";
export const TESTIMONIAL_LIST_FAILED = "TESTIMONIAL_LIST_FAILED";
export const RESET_TESTIMONIAL_LIST_FLAG = "RESET_TESTIMONIAL_LIST_FLAG";
export const REFRESH_TESTIMONIAL_LIST_FLAG = "REFRESH_TESTIMONIAL_LIST_FLAG";
