export const FAQ_LIST = "FAQ_LIST";
export const FAQ_LIST_SUCCESSFUL = "FAQ_LIST_SUCCESSFUL";
export const FAQ_LIST_FAILED = "FAQ_LIST_FAILED";
export const RESET_FAQ_LIST_FLAG = "RESET_FAQ_LIST_FLAG";
export const REFRESH_FAQ_LIST_FLAG = "REFRESH_FAQ_LIST_FLAG";
