export const CATEGORY_SHOW_DETAIL = "CATEGORY_SHOW_DETAIL";
export const CATEGORY_SHOW_DETAIL_SUCCESSFUL = "CATEGORY_SHOW_DETAIL_SUCCESSFUL";
export const CATEGORY_SHOW_DETAIL_FAILED = "CATEGORY_SHOW_DETAIL_FAILED";
export const RESET_CATEGORY_SHOW_DETAIL_FLAG = "RESET_CATEGORY_SHOW_DETAIL_FLAG";
