export const INDIVIDUAL_SHOW_DETAIL = "INDIVIDUAL_SHOW_DETAIL";
export const INDIVIDUAL_SHOW_DETAIL_SUCCESSFUL = "INDIVIDUAL_SHOW_DETAIL_SUCCESSFUL";
export const INDIVIDUAL_SHOW_DETAIL_FAILED = "INDIVIDUAL_SHOW_DETAIL_FAILED";
export const RESET_INDIVIDUAL_SHOW_DETAIL_FLAG = "RESET_INDIVIDUAL_SHOW_DETAIL_FLAG";
