export const SAVE_PARTNER = "SAVE_PARTNER";
export const SAVE_PARTNER_SUCCESSFUL = "SAVE_PARTNER_SUCCESSFUL";
export const SAVE_PARTNER_FAILED = "SAVE_PARTNER_FAILED";

export const DELETE_PARTNER = "DELETE_PARTNER";
export const DELETE_PARTNER_SUCCESSFUL = "DELETE_PARTNER_SUCCESSFUL";
export const DELETE_PARTNER_FAILED = "DELETE_PARTNER_FAILED";

export const RESET_SAVE_PARTNER_FLAG = "RESET_SAVE_PARTNER_FLAG";
