export const CAREER_LIST = "CAREER_LIST";
export const CAREER_LIST_SUCCESSFUL = "CAREER_LIST_SUCCESSFUL";
export const CAREER_LIST_FAILED = "CAREER_LIST_FAILED";
export const RESET_CAREER_LIST_FLAG = "RESET_CAREER_LIST_FLAG";
export const REFRESH_CAREER_LIST_FLAG = "REFRESH_CAREER_LIST_FLAG";
