export const EXCHANGE_SHOW_DETAIL = "EXCHANGE_SHOW_DETAIL";
export const EXCHANGE_SHOW_DETAIL_SUCCESSFUL = "EXCHANGE_SHOW_DETAIL_SUCCESSFUL";
export const EXCHANGE_SHOW_DETAIL_FAILED = "EXCHANGE_SHOW_DETAIL_FAILED";
export const RESET_EXCHANGE_SHOW_DETAIL_FLAG = "RESET_EXCHANGE_SHOW_DETAIL_FLAG";
