export const CREATE_PAGE_BANNER = "CREATE_PAGE_BANNER";
export const CREATE_PAGE_BANNER_SUCCESSFUL = "CREATE_PAGE_BANNER_SUCCESSFUL";
export const CREATE_PAGE_BANNER_FAILED = "CREATE_PAGE_BANNER_FAILED";

export const DELETE_PAGE_BANNER = "DELETE_PAGE_BANNER";
export const DELETE_PAGE_BANNER_SUCCESSFUL = "DELETE_PAGE_BANNER_SUCCESSFUL";
export const DELETE_PAGE_BANNER_FAILED = "DELETE_PAGE_BANNER_FAILED";

export const RESET_CREATE_PAGE_BANNER_FLAG = "RESET_CREATE_PAGE_BANNER_FLAG";
