export const PROJECT_CATEGORY_SHOW_DETAIL = "PROJECT_CATEGORY_SHOW_DETAIL";
export const PROJECT_CATEGORY_SHOW_DETAIL_SUCCESSFUL = "PROJECT_CATEGORY_SHOW_DETAIL_SUCCESSFUL";
export const PROJECT_CATEGORY_SHOW_DETAIL_FAILED = "PROJECT_CATEGORY_SHOW_DETAIL_FAILED";
export const RESET_PROJECT_CATEGORY_SHOW_DETAIL_FLAG = "RESET_PROJECT_CATEGORY_SHOW_DETAIL_FLAG";
