export const TRADING_LIST = "TRADING_LIST";
export const TRADING_LIST_SUCCESSFUL = "TRADING_LIST_SUCCESSFUL";
export const TRADING_LIST_FAILED = "TRADING_LIST_FAILED";
export const RESET_TRADING_LIST_FLAG = "RESET_TRADING_LIST_FLAG";
export const REFRESH_TRADING_LIST_FLAG = "REFRESH_TRADING_LIST_FLAG";
