export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_SUCCESSFUL = "CREATE_TESTIMONIAL_SUCCESSFUL";
export const CREATE_TESTIMONIAL_FAILED = "CREATE_TESTIMONIAL_FAILED";

export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_SUCCESSFUL = "DELETE_TESTIMONIAL_SUCCESSFUL";
export const DELETE_TESTIMONIAL_FAILED = "DELETE_TESTIMONIAL_FAILED";

export const RESET_CREATE_TESTIMONIAL_FLAG = "RESET_CREATE_TESTIMONIAL_FLAG";
