export const USER_LIST = "USER_LIST";
export const USER_LIST_SUCCESSFUL = "USER_LIST_SUCCESSFUL";
export const USER_LIST_FAILED = "USER_LIST_FAILED";
export const RESET_USER_LIST_FLAG = "RESET_USER_LIST_FLAG";
export const REFRESH_USER_LIST_FLAG = "REFRESH_USER_LIST_FLAG";
