export const CURRENCY_SHOW_DETAIL = "CURRENCY_SHOW_DETAIL";
export const CURRENCY_SHOW_DETAIL_SUCCESSFUL = "CURRENCY_SHOW_DETAIL_SUCCESSFUL";
export const CURRENCY_SHOW_DETAIL_FAILED = "CURRENCY_SHOW_DETAIL_FAILED";
export const RESET_CURRENCY_SHOW_DETAIL_FLAG = "RESET_CURRENCY_SHOW_DETAIL_FLAG";
