export const BANNER_SHOW_DETAIL = "BANNER_SHOW_DETAIL";
export const BANNER_SHOW_DETAIL_SUCCESSFUL = "BANNER_SHOW_DETAIL_SUCCESSFUL";
export const BANNER_SHOW_DETAIL_FAILED = "BANNER_SHOW_DETAIL_FAILED";
export const RESET_BANNER_SHOW_DETAIL_FLAG = "RESET_BANNER_SHOW_DETAIL_FLAG";
