export const CREATE_FAQ = "CREATE_FAQ";
export const CREATE_FAQ_SUCCESSFUL = "CREATE_FAQ_SUCCESSFUL";
export const CREATE_FAQ_FAILED = "CREATE_FAQ_FAILED";

export const DELETE_FAQ = "DELETE_FAQ";
export const DELETE_FAQ_SUCCESSFUL = "DELETE_FAQ_SUCCESSFUL";
export const DELETE_FAQ_FAILED = "DELETE_FAQ_FAILED";

export const RESET_CREATE_FAQ_FLAG = "RESET_CREATE_FAQ_FLAG";
