export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_SUCCESSFUL = "PRODUCT_LIST_SUCCESSFUL";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
export const RESET_PRODUCT_LIST_FLAG = "RESET_PRODUCT_LIST_FLAG";
export const REFRESH_PRODUCT_LIST_FLAG = "REFRESH_PRODUCT_LIST_FLAG";
