export const ROLE_LIST = "ROLE_LIST";
export const ROLE_LIST_SUCCESSFUL = "ROLE_LIST_SUCCESSFUL";
export const ROLE_LIST_FAILED = "ROLE_LIST_FAILED";
export const RESET_ROLE_LIST_FLAG = "RESET_ROLE_LIST_FLAG";
export const REFRESH_ROLE_LIST_FLAG = "REFRESH_ROLE_LIST_FLAG";
