export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const SAVE_PRODUCT_SUCCESSFUL = "SAVE_PRODUCT_SUCCESSFUL";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESSFUL = "DELETE_PRODUCT_SUCCESSFUL";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const RESET_SAVE_PRODUCT_FLAG = "RESET_SAVE_PRODUCT_FLAG";
