export const NEWS_SHOW_DETAIL = "NEWS_SHOW_DETAIL";
export const NEWS_SHOW_DETAIL_SUCCESSFUL = "NEWS_SHOW_DETAIL_SUCCESSFUL";
export const NEWS_SHOW_DETAIL_FAILED = "NEWS_SHOW_DETAIL_FAILED";
export const RESET_NEWS_SHOW_DETAIL_FLAG = "RESET_NEWS_SHOW_DETAIL_FLAG";
