export const PAGE_BANNER_SHOW_DETAIL = "PAGE_BANNER_SHOW_DETAIL";
export const PAGE_BANNER_SHOW_DETAIL_SUCCESSFUL = "PAGE_BANNER_SHOW_DETAIL_SUCCESSFUL";
export const PAGE_BANNER_SHOW_DETAIL_FAILED = "PAGE_BANNER_SHOW_DETAIL_FAILED";
export const RESET_PAGE_BANNER_SHOW_DETAIL_FLAG = "RESET_PAGE_BANNER_SHOW_DETAIL_FLAG";
