export const SAVE_BANNER = "SAVE_BANNER";
export const SAVE_BANNER_SUCCESSFUL = "SAVE_BANNER_SUCCESSFUL";
export const SAVE_BANNER_FAILED = "SAVE_BANNER_FAILED";

export const DELETE_BANNER = "DELETE_BANNER";
export const DELETE_BANNER_SUCCESSFUL = "DELETE_BANNER_SUCCESSFUL";
export const DELETE_BANNER_FAILED = "DELETE_BANNER_FAILED";

export const RESET_SAVE_BANNER_FLAG = "RESET_SAVE_BANNER_FLAG";
