export const SERVICE_SHOW_DETAIL = "SERVICE_SHOW_DETAIL";
export const SERVICE_SHOW_DETAIL_SUCCESSFUL = "SERVICE_SHOW_DETAIL_SUCCESSFUL";
export const SERVICE_SHOW_DETAIL_FAILED = "SERVICE_SHOW_DETAIL_FAILED";
export const RESET_SERVICE_SHOW_DETAIL_FLAG = "RESET_SERVICE_SHOW_DETAIL_FLAG";
