export const BANNER_LIST = "BANNER_LIST";
export const BANNER_LIST_SUCCESSFUL = "BANNER_LIST_SUCCESSFUL";
export const BANNER_LIST_FAILED = "BANNER_LIST_FAILED";
export const RESET_BANNER_LIST_FLAG = "RESET_BANNER_LIST_FLAG";
export const REFRESH_BANNER_LIST_FLAG = "REFRESH_BANNER_LIST_FLAG";
