export const TESTIMONIAL_SHOW_DETAIL = "TESTIMONIAL_SHOW_DETAIL";
export const TESTIMONIAL_SHOW_DETAIL_SUCCESSFUL = "TESTIMONIAL_SHOW_DETAIL_SUCCESSFUL";
export const TESTIMONIAL_SHOW_DETAIL_FAILED = "TESTIMONIAL_SHOW_DETAIL_FAILED";
export const RESET_TESTIMONIAL_SHOW_DETAIL_FLAG = "RESET_TESTIMONIAL_SHOW_DETAIL_FLAG";
