export const APPLICATION_SHOW_DETAIL = "APPLICATION_SHOW_DETAIL";
export const APPLICATION_SHOW_DETAIL_SUCCESSFUL = "APPLICATION_SHOW_DETAIL_SUCCESSFUL";
export const APPLICATION_SHOW_DETAIL_FAILED = "APPLICATION_SHOW_DETAIL_FAILED";
export const RESET_APPLICATION_SHOW_DETAIL_FLAG = "RESET_APPLICATION_SHOW_DETAIL_FLAG";
