export const SAVE_ROLE = "SAVE_ROLE";
export const SAVE_ROLE_SUCCESSFUL = "SAVE_ROLE_SUCCESSFUL";
export const SAVE_ROLE_FAILED = "SAVE_ROLE_FAILED";

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESSFUL = "DELETE_ROLE_SUCCESSFUL";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";

export const RESET_SAVE_ROLE_FLAG = "RESET_SAVE_ROLE_FLAG";
