export const FAQ_SHOW_DETAIL = "FAQ_SHOW_DETAIL";
export const FAQ_SHOW_DETAIL_SUCCESSFUL = "FAQ_SHOW_DETAIL_SUCCESSFUL";
export const FAQ_SHOW_DETAIL_FAILED = "FAQ_SHOW_DETAIL_FAILED";
export const RESET_FAQ_SHOW_DETAIL_FLAG = "RESET_FAQ_SHOW_DETAIL_FLAG";
