export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_LIST_SUCCESSFUL = "CATEGORY_LIST_SUCCESSFUL";
export const CATEGORY_LIST_FAILED = "CATEGORY_LIST_FAILED";
export const RESET_CATEGORY_LIST_FLAG = "RESET_CATEGORY_LIST_FLAG";
export const REFRESH_CATEGORY_LIST_FLAG = "REFRESH_CATEGORY_LIST_FLAG";
