export const NEWS_LIST = "NEWS_LIST";
export const NEWS_LIST_SUCCESSFUL = "NEWS_LIST_SUCCESSFUL";
export const NEWS_LIST_FAILED = "NEWS_LIST_FAILED";
export const RESET_NEWS_LIST_FLAG = "RESET_NEWS_LIST_FLAG";
export const REFRESH_NEWS_LIST_FLAG = "REFRESH_NEWS_LIST_FLAG";
