export const SAVE_NEWS = "SAVE_NEWS";
export const SAVE_NEWS_SUCCESSFUL = "SAVE_NEWS_SUCCESSFUL";
export const SAVE_NEWS_FAILED = "SAVE_NEWS_FAILED";

export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_SUCCESSFUL = "DELETE_NEWS_SUCCESSFUL";
export const DELETE_NEWS_FAILED = "DELETE_NEWS_FAILED";

export const RESET_SAVE_NEWS_FLAG = "RESET_SAVE_NEWS_FLAG";
