export const SERVICE_LIST = "SERVICE_LIST";
export const SERVICE_LIST_SUCCESSFUL = "SERVICE_LIST_SUCCESSFUL";
export const SERVICE_LIST_FAILED = "SERVICE_LIST_FAILED";
export const RESET_SERVICE_LIST_FLAG = "RESET_SERVICE_LIST_FLAG";
export const REFRESH_SERVICE_LIST_FLAG = "REFRESH_SERVICE_LIST_FLAG";
