export const CORPORATE_SHOW_DETAIL = "CORPORATE_SHOW_DETAIL";
export const CORPORATE_SHOW_DETAIL_SUCCESSFUL = "CORPORATE_SHOW_DETAIL_SUCCESSFUL";
export const CORPORATE_SHOW_DETAIL_FAILED = "CORPORATE_SHOW_DETAIL_FAILED";
export const RESET_CORPORATE_SHOW_DETAIL_FLAG = "RESET_CORPORATE_SHOW_DETAIL_FLAG";
