export const PROJECT_CATEGORY_LIST = "PROJECT_CATEGORY_LIST";
export const PROJECT_CATEGORY_LIST_SUCCESSFUL = "PROJECT_CATEGORY_LIST_SUCCESSFUL";
export const PROJECT_CATEGORY_LIST_FAILED = "PROJECT_CATEGORY_LIST_FAILED";
export const RESET_PROJECT_CATEGORY_LIST_FLAG = "RESET_PROJECT_CATEGORY_LIST_FLAG";
export const REFRESH_PROJECT_CATEGORY_LIST_FLAG = "REFRESH_PROJECT_CATEGORY_LIST_FLAG";
