export const EXCHANGE_LIST = "EXCHANGE_LIST";
export const EXCHANGE_LIST_SUCCESSFUL = "EXCHANGE_LIST_SUCCESSFUL";
export const EXCHANGE_LIST_FAILED = "EXCHANGE_LIST_FAILED";
export const RESET_EXCHANGE_LIST_FLAG = "RESET_EXCHANGE_LIST_FLAG";
export const REFRESH_EXCHANGE_LIST_FLAG = "REFRESH_EXCHANGE_LIST_FLAG";
