export const INDIVIDUAL_LIST = "INDIVIDUAL_LIST";
export const INDIVIDUAL_LIST_SUCCESSFUL = "INDIVIDUAL_LIST_SUCCESSFUL";
export const INDIVIDUAL_LIST_FAILED = "INDIVIDUAL_LIST_FAILED";
export const RESET_INDIVIDUAL_LIST_FLAG = "RESET_INDIVIDUAL_LIST_FLAG";
export const REFRESH_INDIVIDUAL_LIST_FLAG = "REFRESH_INDIVIDUAL_LIST_FLAG";

export const DELETE_INDIVIDUAL = "DELETE_INDIVIDUAL";
export const DELETE_INDIVIDUAL_SUCCESSFUL = "DELETE_INDIVIDUAL_SUCCESSFUL";
export const DELETE_INDIVIDUAL_FAILED = "DELETE_INDIVIDUAL_FAILED";
