export const PARTNER_SHOW_DETAIL = "PARTNER_SHOW_DETAIL";
export const PARTNER_SHOW_DETAIL_SUCCESSFUL = "PARTNER_SHOW_DETAIL_SUCCESSFUL";
export const PARTNER_SHOW_DETAIL_FAILED = "PARTNER_SHOW_DETAIL_FAILED";
export const RESET_PARTNER_SHOW_DETAIL_FLAG = "RESET_PARTNER_SHOW_DETAIL_FLAG";
