export const AWARD_SHOW_DETAIL = "AWARD_SHOW_DETAIL";
export const AWARD_SHOW_DETAIL_SUCCESSFUL = "AWARD_SHOW_DETAIL_SUCCESSFUL";
export const AWARD_SHOW_DETAIL_FAILED = "AWARD_SHOW_DETAIL_FAILED";
export const RESET_AWARD_SHOW_DETAIL_FLAG = "RESET_AWARD_SHOW_DETAIL_FLAG";
