export const AWARD_LIST = "AWARD_LIST";
export const AWARD_LIST_SUCCESSFUL = "AWARD_LIST_SUCCESSFUL";
export const AWARD_LIST_FAILED = "AWARD_LIST_FAILED";
export const RESET_AWARD_LIST_FLAG = "RESET_AWARD_LIST_FLAG";
export const REFRESH_AWARD_LIST_FLAG = "REFRESH_AWARD_LIST_FLAG";
