export const CAREER_SHOW_DETAIL = "CAREER_SHOW_DETAIL";
export const CAREER_SHOW_DETAIL_SUCCESSFUL = "CAREER_SHOW_DETAIL_SUCCESSFUL";
export const CAREER_SHOW_DETAIL_FAILED = "CAREER_SHOW_DETAIL_FAILED";
export const RESET_CAREER_SHOW_DETAIL_FLAG = "RESET_CAREER_SHOW_DETAIL_FLAG";
