export const TEAM_SHOW_DETAIL = "TEAM_SHOW_DETAIL";
export const TEAM_SHOW_DETAIL_SUCCESSFUL = "TEAM_SHOW_DETAIL_SUCCESSFUL";
export const TEAM_SHOW_DETAIL_FAILED = "TEAM_SHOW_DETAIL_FAILED";
export const RESET_TEAM_SHOW_DETAIL_FLAG = "RESET_TEAM_SHOW_DETAIL_FLAG";
