export const SAVE_CURRENCY = "SAVE_CURRENCY";
export const SAVE_CURRENCY_SUCCESSFUL = "SAVE_CURRENCY_SUCCESSFUL";
export const SAVE_CURRENCY_FAILED = "SAVE_CURRENCY_FAILED";

export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const DELETE_CURRENCY_SUCCESSFUL = "DELETE_CURRENCY_SUCCESSFUL";
export const DELETE_CURRENCY_FAILED = "DELETE_CURRENCY_FAILED";

export const RESET_SAVE_CURRENCY_FLAG = "RESET_SAVE_CURRENCY_FLAG";
