export const CURRENCY_LIST = "CURRENCY_LIST";
export const CURRENCY_LIST_SUCCESSFUL = "CURRENCY_LIST_SUCCESSFUL";
export const CURRENCY_LIST_FAILED = "CURRENCY_LIST_FAILED";
export const RESET_CURRENCY_LIST_FLAG = "RESET_CURRENCY_LIST_FLAG";
export const REFRESH_CURRENCY_LIST_FLAG = "REFRESH_CURRENCY_LIST_FLAG";
