export const PARTNER_LIST = "PARTNER_LIST";
export const PARTNER_LIST_SUCCESSFUL = "PARTNER_LIST_SUCCESSFUL";
export const PARTNER_LIST_FAILED = "PARTNER_LIST_FAILED";
export const RESET_PARTNER_LIST_FLAG = "RESET_PARTNER_LIST_FLAG";
export const REFRESH_PARTNER_LIST_FLAG = "REFRESH_PARTNER_LIST_FLAG";
