export const ROLE_SHOW_DETAIL = "ROLE_SHOW_DETAIL";
export const ROLE_SHOW_DETAIL_SUCCESSFUL = "ROLE_SHOW_DETAIL_SUCCESSFUL";
export const ROLE_SHOW_DETAIL_FAILED = "ROLE_SHOW_DETAIL_FAILED";
export const RESET_ROLE_SHOW_DETAIL_FLAG = "RESET_ROLE_SHOW_DETAIL_FLAG";
