export const SAVE_TEAM = "SAVE_TEAM";
export const SAVE_TEAM_SUCCESSFUL = "SAVE_TEAM_SUCCESSFUL";
export const SAVE_TEAM_FAILED = "SAVE_TEAM_FAILED";

export const DELETE_TEAM = "DELETE_TEAM";
export const DELETE_TEAM_SUCCESSFUL = "DELETE_TEAM_SUCCESSFUL";
export const DELETE_TEAM_FAILED = "DELETE_TEAM_FAILED";

export const RESET_SAVE_TEAM_FLAG = "RESET_SAVE_TEAM_FLAG";
