export const SAVE_AWARD = "SAVE_AWARD";
export const SAVE_AWARD_SUCCESSFUL = "SAVE_AWARD_SUCCESSFUL";
export const SAVE_AWARD_FAILED = "SAVE_AWARD_FAILED";

export const DELETE_AWARD = "DELETE_AWARD";
export const DELETE_AWARD_SUCCESSFUL = "DELETE_AWARD_SUCCESSFUL";
export const DELETE_AWARD_FAILED = "DELETE_AWARD_FAILED";

export const RESET_SAVE_AWARD_FLAG = "RESET_SAVE_AWARD_FLAG";
