export const FILE_STORAGE = "FILE_STORAGE";
export const FILE_STORAGE_SUCCESSFUL = "FILE_STORAGE_SUCCESSFUL";
export const FILE_STORAGE_FAILED = "FILE_STORAGE_FAILED";
export const RESET_FILE_STORAGE_FLAG = "RESET_FILE_STORAGE_FLAG";
