export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESSFUL = "CREATE_CATEGORY_SUCCESSFUL";
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESSFUL = "DELETE_CATEGORY_SUCCESSFUL";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const RESET_CREATE_CATEGORY_FLAG = "RESET_CREATE_CATEGORY_FLAG";
