export const SAVE_EXCHANGE = "SAVE_EXCHANGE";
export const SAVE_EXCHANGE_SUCCESSFUL = "SAVE_EXCHANGE_SUCCESSFUL";
export const SAVE_EXCHANGE_FAILED = "SAVE_EXCHANGE_FAILED";

export const DELETE_EXCHANGE = "DELETE_EXCHANGE";
export const DELETE_EXCHANGE_SUCCESSFUL = "DELETE_EXCHANGE_SUCCESSFUL";
export const DELETE_EXCHANGE_FAILED = "DELETE_EXCHANGE_FAILED";

export const RESET_SAVE_EXCHANGE_FLAG = "RESET_SAVE_EXCHANGE_FLAG";
