export const CREATE_CAREER = "CREATE_CAREER";
export const CREATE_CAREER_SUCCESSFUL = "CREATE_CAREER_SUCCESSFUL";
export const CREATE_CAREER_FAILED = "CREATE_CAREER_FAILED";

export const DELETE_CAREER = "DELETE_CAREER";
export const DELETE_CAREER_SUCCESSFUL = "DELETE_CAREER_SUCCESSFUL";
export const DELETE_CAREER_FAILED = "DELETE_CAREER_FAILED";

export const RESET_CREATE_CAREER_FLAG = "RESET_CREATE_CAREER_FLAG";
