export const SAVE_SERVICE = "SAVE_SERVICE";
export const SAVE_SERVICE_SUCCESSFUL = "SAVE_SERVICE_SUCCESSFUL";
export const SAVE_SERVICE_FAILED = "SAVE_SERVICE_FAILED";

export const DELETE_SERVICE = "DELETE_SERVICE";
export const DELETE_SERVICE_SUCCESSFUL = "DELETE_SERVICE_SUCCESSFUL";
export const DELETE_SERVICE_FAILED = "DELETE_SERVICE_FAILED";

export const RESET_SAVE_SERVICE_FLAG = "RESET_SAVE_SERVICE_FLAG";
