export const TRADING_SHOW_DETAIL = "TRADING_SHOW_DETAIL";
export const TRADING_SHOW_DETAIL_SUCCESSFUL = "TRADING_SHOW_DETAIL_SUCCESSFUL";
export const TRADING_SHOW_DETAIL_FAILED = "TRADING_SHOW_DETAIL_FAILED";
export const RESET_TRADING_SHOW_DETAIL_FLAG = "RESET_TRADING_SHOW_DETAIL_FLAG";
