export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESSFUL = "CREATE_USER_SUCCESSFUL";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESSFUL = "DELETE_USER_SUCCESSFUL";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const RESET_CREATE_USER_FLAG = "RESET_CREATE_USER_FLAG";
