export const APPLICATION_LIST = "APPLICATION_LIST";
export const APPLICATION_LIST_SUCCESSFUL = "APPLICATION_LIST_SUCCESSFUL";
export const APPLICATION_LIST_FAILED = "APPLICATION_LIST_FAILED";
export const RESET_APPLICATION_LIST_FLAG = "RESET_APPLICATION_LIST_FLAG";
export const REFRESH_APPLICATION_LIST_FLAG = "REFRESH_APPLICATION_LIST_FLAG";

export const DELETE_APPLICATION = "DELETE_APPLICATION";
export const DELETE_APPLICATION_SUCCESSFUL = "DELETE_APPLICATION_SUCCESSFUL";
export const DELETE_APPLICATION_FAILED = "DELETE_APPLICATION_FAILED";
