export const CHANGE_PWD_USER = "CHANGE_PWD_USER";
export const CHANGE_PWD_USER_SUCCESSFUL = "CHANGE_PWD_USER_SUCCESSFUL";
export const CHANGE_PWD_USER_FAILED = "CHANGE_PWD_USER_FAILED";
export const RESET_CHANGE_PWD_FLAG = "RESET_CHANGE_PWD_FLAG";
export const CHANGE_PWD_USER_SUCCESSFUL_REDIRECT = "CHANGE_PWD_USER_SUCCESSFUL_REDIRECT";
