export const USER_SHOW_DETAIL = "USER_SHOW_DETAIL";
export const USER_SHOW_DETAIL_SUCCESSFUL = "USER_SHOW_DETAIL_SUCCESSFUL";
export const USER_SHOW_DETAIL_FAILED = "USER_SHOW_DETAIL_FAILED";
export const RESET_USER_SHOW_DETAIL_FLAG = "RESET_USER_SHOW_DETAIL_FLAG";
