export const SAVE_TRADING = "SAVE_TRADING";
export const SAVE_TRADING_SUCCESSFUL = "SAVE_TRADING_SUCCESSFUL";
export const SAVE_TRADING_FAILED = "SAVE_TRADING_FAILED";

export const DELETE_TRADING = "DELETE_TRADING";
export const DELETE_TRADING_SUCCESSFUL = "DELETE_TRADING_SUCCESSFUL";
export const DELETE_TRADING_FAILED = "DELETE_TRADING_FAILED";

export const RESET_SAVE_TRADING_FLAG = "RESET_SAVE_TRADING_FLAG";
