export const PAGE_BANNER_LIST = "PAGE_BANNER_LIST";
export const PAGE_BANNER_LIST_SUCCESSFUL = "PAGE_BANNER_LIST_SUCCESSFUL";
export const PAGE_BANNER_LIST_FAILED = "PAGE_BANNER_LIST_FAILED";
export const RESET_PAGE_BANNER_LIST_FLAG = "RESET_PAGE_BANNER_LIST_FLAG";
export const REFRESH_PAGE_BANNER_LIST_FLAG = "REFRESH_PAGE_BANNER_LIST_FLAG";
