export const SAVE_SITE_SETTING = "SAVE_SITE_SETTING";
export const SAVE_SITE_SETTING_SUCCESSFUL = "SAVE_SITE_SETTING_SUCCESSFUL";
export const SAVE_SITE_SETTING_FAILED = "SAVE_SITE_SETTING_FAILED";

export const GET_SITE_SETTING = "GET_SITE_SETTING";
export const GET_SITE_SETTING_SUCCESSFUL = "GET_SITE_SETTING_SUCCESSFUL";
export const GET_SITE_SETTING_FAILED = "GET_SITE_SETTING_FAILED";

export const RESET_SAVE_SITE_SETTING_FLAG = "RESET_SAVE_SITE_SETTING_FLAG";
