export const PRODUCT_SHOW_DETAIL = "PRODUCT_SHOW_DETAIL";
export const PRODUCT_SHOW_DETAIL_SUCCESSFUL = "PRODUCT_SHOW_DETAIL_SUCCESSFUL";
export const PRODUCT_SHOW_DETAIL_FAILED = "PRODUCT_SHOW_DETAIL_FAILED";
export const RESET_PRODUCT_SHOW_DETAIL_FLAG = "RESET_PRODUCT_SHOW_DETAIL_FLAG";
