export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const API_ERROR = "LOGIN_API_ERROR";

export const SOCIAL_LOGIN = "SOCIAL_LOGIN";

export const RESET_LOGIN_FLAG = "RESET_LOGIN_FLAG";

export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const USER_DETAIL = "USER_DETAIL";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESSFUL = "UPDATE_USER_SUCCESSFUL";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const RESET_UPDATE_USER_FLAG = "RESET_UPDATE_USER_FLAG";
