export const TEAM_LIST = "TEAM_LIST";
export const TEAM_LIST_SUCCESSFUL = "TEAM_LIST_SUCCESSFUL";
export const TEAM_LIST_FAILED = "TEAM_LIST_FAILED";
export const RESET_TEAM_LIST_FLAG = "RESET_TEAM_LIST_FLAG";
export const REFRESH_TEAM_LIST_FLAG = "REFRESH_TEAM_LIST_FLAG";
